### ISSUE TITLE
Make Stomp's Host as Options

### ISSUE THREAD

**Issue by shariq-iways** [walterwanderley/xk6-stomp#1]
Default Host of Rabbiqmq and ActiveMq is different. As Host is currently not in options, so stomp can't be connected with rabbitmq default host. For testing in rabbitmq, I have hardcodedly added hostname in code. It's working with rabbitmq now.
You can check sample change in here.
https://github.com/shariq-iways/xk6-stomp/commit/50292a2fab80a686f413abec05ce6913aa65000f

**Comment by walterwanderley** [comment]
Hi @shariq-iways thanks for your contribution!

I added the Host option in the latest version (v0.0.12).

https://github.com/walterwanderley/xk6-stomp/blob/main/_examples/connection_params.js#L13

**Comment by shariq-iways** [comment]
Thank you for adding this feature. I will close this issue
