### ISSUE TITLE
Invalid memory address or nil pointer dereference while tests stomp over websocket

### ISSUE THREAD

**Issue by vorrarit** [walterwanderley/xk6-stomp#4]
I've run xk6-stomp to test stomp over websocket implemented by using spring boot and get the following error during teardown.

> DEBU[0060] Executor finished successfully                executor=default startTime=0s type=per-vu-iterations
DEBU[0060] Running teardown()                            phase=local-execution-scheduler-run
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x9caf61]
default   [--------------------------------------] 1 VUs  01m00.0s/10m0s  0/1 iters, 1 per VU
goroutine 87 [running]:
go.k6.io/k6/metrics.PushIfNotDone(...)
	go.k6.io/k6@v0.40.0/metrics/sample.go:119
github.com/walterwanderley/xk6-stomp/stomp.(*Client).reportStats(0xc0015f4cf0, 0xc000771680, 0x0, {0x0?, 0x0?, 0x2009ca0?}, 0x0)
	github.com/walterwanderley/xk6-stomp@v0.0.25/stomp/stomp.go:388 +0x1a1
github.com/walterwanderley/xk6-stomp/stomp.(*StatsReadWriteClose).Read(0xc0012d6060, {0xc000b34000?, 0x0?, 0xc0022f7ca0?})
	github.com/walterwanderley/xk6-stomp@v0.0.25/stomp/stats.go:94 +0x7c

**Comment by walterwanderley** [comment]
Hi @vorrarit
 please, try the new version v0.0.26

**Comment by vorrarit** [comment]
Thank you.  It's work perfect now.
