### ISSUE TITLE
SockJS messages

### ISSUE THREAD

**Issue by wasndak** [walterwanderley/xk6-stomp#5]
Hi

I have installed your plugin, did connect to the server but got read error for first message I've got. Issue here is that server is sending messages in sockJS. I'd like to ask if there is plan to implement sockJS if server uses this kind of messages.

Thank you.

**Comment by walterwanderley** [comment]
> Hi
> 
> I have installed your plugin, did connect to the server but got read error for first message I've got. Issue here is that server is sending messages in sockJS. I'd like to ask if there is plan to implement sockJS if server uses this kind of messages.
> 
> Thank you.

Hi @wasndak !

I've never tried sockJS on the server. Is It possible? Have you look the websocket example? 
https://github.com/walterwanderley/xk6-stomp/blob/main/_examples/websocket.js

**Comment by wasndak** [comment]
> > Hi
> > I have installed your plugin, did connect to the server but got read error for first message I've got. Issue here is that server is sending messages in sockJS. I'd like to ask if there is plan to implement sockJS if server uses this kind of messages.
> > Thank you.
> 
> Hi @wasndak !
> 
> I've never tried sockJS on the server. Is It possible? Have you look the websocket example? https://github.com/walterwanderley/xk6-stomp/blob/main/_examples/websocket.js

Hi Walter,
thank you for reply. I've worked on it for few days, without success. Implement sockJS should be possible, but as far as I know, its old solution of WS, and now its not used so much. I use another tool for it, and this was just a try.
Log fyi : 
![image](https://user-images.githubusercontent.com/35810501/203812192-ad811975-6966-422b-adb3-587c7b77819c.png)
